In [0]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
fileid_1='1LpuTmUqO0qLuiZt-nNUOY1Urbye2K5f-'
fileid_2='1ILzNrunsdUjO_2y77MCneBf7CtsyjrYg'
downloaded=drive.CreateFile({'id':fileid_1})
downloaded.GetContentFile('FAKENEWSDETECT_DATASET.csv')

downloaded=drive.CreateFile({'id':fileid_2})
downloaded.GetContentFile('fake_or_real_news.csv')

In [0]:

import pandas as pd    #data processing
import numpy as np     #linear algebra
import matplotlib.pyplot as plt   #plotting graphs
from mpl_toolkits.mplot3d import Axes3D   #3d image for an object
from sklearn.preprocessing import StandardScaler    #Standardization of data
import os

In [0]:
#nRowsRead=1000
df1=pd.read_csv('FAKENEWSDETECT_DATASET.csv',nrows=5000)
df1_val=pd.read_csv('fake_or_real_news.csv',nrows=5000)


In [6]:
from sklearn.model_selection import train_test_split
df2 = df1[pd.notnull(df1['fake'])]
df2 = df2[pd.notnull(df2['news'])]
y=(df2['fake']=='0').astype(int)
df2_val = df1_val[pd.notnull(df1_val['label'])]
df2_val = df2_val[pd.notnull(df2_val['title'])]
y_val=(df2_val['label']=='REAL').astype(int)

/usr/local/lib/python3.6/dist-packages/pandas/core/ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


In [7]:
df1['fake'].unique().tolist()


[nan, 1.0, 0.0]

In [8]:
df1_val['label'].unique().tolist()

['FAKE', 'REAL']

In [10]:
print(sum(df2['fake']==0))
print(sum(df2_val['label']=='REAL'))

2437
2517


In [0]:
#ds=pd.read_excel('News Dataset.xlsx', nrows=49)
 
x_aug =df2['news']
x_aug_val = df2_val['title']
#col_y = pd.DataFrame([1 for x in range(49)])
y_aug =y
y_aug_val = y_val

In [12]:
print(df2.shape)
print(y.shape)
print(df2_val.shape)
print(y_val.shape)
#print(y[0])

(2477, 3)
(2477,)
(5000, 4)
(5000,)


In [0]:
X_train, X_test, y_train, y_test = train_test_split(x_aug, y_aug, test_size=0.25, random_state=42)

In [14]:
X_train.head()

1737    'Big Daddy' laps up Cipla after Q1 nos beat fo...
3281     Kartarpur Corridor: In half-hearted attempt, ...
3863     In Japan, the business of watching whales is ...
4477     Pro-Balochistan activists disrupt Imran Khan'...
2144     IMF approves $6 billion loan for cash-strappe...
Name: news, dtype: object

In [15]:
X_train.shape

(1857,)

In [16]:
y_train.head()

1737    0
3281    0
3863    0
4477    0
2144    0
Name: fake, dtype: int64

In [17]:
y_train.shape

(1857,)

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
# Initialize the `tfidf_vectorizer` 
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7) 

# Fit and transform the training data 
tfidf_train = tfidf_vectorizer.fit_transform(X_train) 

# Transform the test set 
tfidf_test = tfidf_vectorizer.transform(X_test)

tfidf_validate = tfidf_vectorizer.transform(x_aug_val)

In [19]:
print(tfidf_train.shape)

(1857, 7788)


In [0]:
from sklearn.feature_extraction.text import CountVectorizer
# Initialize the `count_vectorizer` 
count_vectorizer = CountVectorizer(stop_words='english')

# Fit and transform the training data 
count_train = count_vectorizer.fit_transform(X_train) 

# Transform the test set 
count_test = count_vectorizer.transform(X_test)

count_validate = count_vectorizer.transform(x_aug_val)

In [21]:
# Get the feature names of `tfidf_vectorizer` 
print(tfidf_vectorizer.get_feature_names()[-10:])

# Get the feature names of `count_vectorizer` 
print(count_vectorizer.get_feature_names()[:10])

['zone', 'zoo', 'zpdqb', 'zq4vmb6lyuxzq3j50_bybfzti', 'zqdp1decxsqzqwmf3f9yhthjoi3xjjwg', 'ztgrisjaeespgmbngpxgg6newkmtn', 'zu4azo', 'zv1cgf4kmbql76abh2q', 'zyspbx0x9fiol4khoxtvvmifenu2cimc', 'zzjdhsfe']
['00', '000', '001', '00r5ajnpxjwifn4kz_hizgew7b2e4iv3', '01', '02', '02t044543z_1216169853_', '02t162600z_1842575144_', '03', '03am']


In [22]:
count_df = pd.DataFrame(count_train.A, columns=count_vectorizer.get_feature_names())
tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vectorizer.get_feature_names())
difference = set(count_df.columns) - set(tfidf_df.columns)
difference
print(count_df.equals(tfidf_df))
count_df.head()

False


00  000  ...  zyspbx0x9fiol4khoxtvvmifenu2cimc  zzjdhsfe
0   0    0  ...                                 0         0
1   0    0  ...                                 0         0
2   0    0  ...                                 0         0
3   0    0  ...                                 0         0
4   0    0  ...                                 0         0

[5 rows x 7788 columns]

In [23]:
tfidf_df.head()

00  000  ...  zyspbx0x9fiol4khoxtvvmifenu2cimc  zzjdhsfe
0  0.0  0.0  ...                               0.0       0.0
1  0.0  0.0  ...                               0.0       0.0
2  0.0  0.0  ...                               0.0       0.0
3  0.0  0.0  ...                               0.0       0.0
4  0.0  0.0  ...                               0.0       0.0

[5 rows x 7788 columns]

In [24]:
X_train.head()

1737    'Big Daddy' laps up Cipla after Q1 nos beat fo...
3281     Kartarpur Corridor: In half-hearted attempt, ...
3863     In Japan, the business of watching whales is ...
4477     Pro-Balochistan activists disrupt Imran Khan'...
2144     IMF approves $6 billion loan for cash-strappe...
Name: news, dtype: object

In [0]:

def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    See full source and example: 
    http://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html
    
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, cm[i, j],
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [26]:
print(y_train.unique().tolist())

[0]


In [27]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier()
#y_train_vec = tfidf_vectorizer.fit_transform(y_train)
knn.fit(tfidf_train,y_train)
prediction = knn.predict(tfidf_test)
prediction_val = knn.predict(tfidf_validate)
#y_test_vec = tfidf_vectorizer.transform(y_test)
score = accuracy_score(y_test, prediction)
score_val = accuracy_score(y_aug_val, prediction_val)
print("test accuracy:   %0.3f" % score)
print("validation accuracy:   %0.3f" % score_val)

test accuracy:   1.000
validation accuracy:   0.497


In [28]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB() 
#y_train_vec = tfidf_vectorizer.fit_transform(y_train)
#y_test_vec = tfidf_vectorizer.transform(y_test)
clf.fit(tfidf_train, y_train)
pred = clf.predict(tfidf_test)
pred_val=clf.predict(tfidf_validate)
score = accuracy_score(y_test, pred)
score_val = accuracy_score(y_aug_val, pred_val)
print("accuracy:   %0.3f" % score)
print("accuracy:   %0.3f" % score_val)
#print(len(pred))
#print(sum(y_test==1))
#print(sum(pred==1))

accuracy:   1.000
accuracy:   0.497


In [29]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(tfidf_train, y_train)
prediction = rf.predict(tfidf_test)
prediction_val = rf.predict(tfidf_validate)

print('With Random Forest accuracy is: ',accuracy_score(y_test,prediction)) # accuracy
print('With Random Forest accuracy is: ',accuracy_score(y_aug_val,prediction_val)) 

With Random Forest accuracy is:  1.0
With Random Forest accuracy is:  0.4966


/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [30]:
y_aug_val

0       0
1       0
2       1
3       0
4       1
5       0
6       0
7       1
8       1
9       1
10      1
11      1
12      0
13      0
14      1
15      1
16      0
17      0
18      1
19      1
20      1
21      0
22      1
23      1
24      0
25      1
26      1
27      1
28      1
29      0
       ..
4970    1
4971    1
4972    1
4973    0
4974    0
4975    0
4976    1
4977    0
4978    0
4979    0
4980    0
4981    0
4982    0
4983    0
4984    0
4985    1
4986    1
4987    0
4988    0
4989    1
4990    1
4991    1
4992    1
4993    0
4994    1
4995    1
4996    0
4997    0
4998    0
4999    1
Name: label, Length: 5000, dtype: int64

In [31]:
print(sum(prediction_val==1))
prediction_val.shape

0


(5000,)

In [32]:
df2.head()

news  fake source
1  Majority of farm animal vets report being inju...   1.0    BVA
3  Vets and animal welfare experts encouraged to ...   1.0    BVA
5  Call for top pics as BVA launches 2019 Veterin...   1.0    BVA
7  NI vets applaud swift action as African Swine ...   1.0    BVA
9  Expert speakers to go ‘behind the headlines’ a...   1.0    BVA

In [0]:
def clean_data(dataframe):
# Drop duplicate rows
    dataframe.drop_duplicates(subset='news', inplace=True)
    
    # Remove punctation
    dataframe['news'] = dataframe['news'].str.replace('[^\w\s]',' ')
# Remove numbers 
    dataframe['news'] = dataframe['news'].str.replace('[^A-Za-z]',' ')
# Make sure any double-spaces are single 
    dataframe['news'] = dataframe['news'].str.replace('  ',' ')
    dataframe['news'] = dataframe['news'].str.replace('  ',' ')
# Transform all text to lowercase
    dataframe['news'] = dataframe['news'].str.lower()
    
    print("New shape:", dataframe.shape)
    return dataframe.head()

In [36]:
clean_data(df2)

New shape: (1048, 3)


news  fake source
1  majority of farm animal vets report being inju...   1.0    BVA
3  vets and animal welfare experts encouraged to ...   1.0    BVA
5  call for top pics as bva launches  veterinary ...   1.0    BVA
7  ni vets applaud swift action as african swine ...   1.0    BVA
9  expert speakers to go behind the headlines at ...   1.0    BVA

In [0]:
from sklearn.model_selection import train_test_split
y = df2['news'] 
#X_train, X_test, y_train, y_test = train_test_split(ds['Body'], y, test_size=0.33, random_state=53)

In [39]:
# Initialize the `tfidf_vectorizer` 
#tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7) 

# Fit and transform the training data 
#tfidf_evaluate = tfidf_vectorizer.fit_transform(y) 
print(y.shape)
# Transform the test set 
tfidf_evaluate = tfidf_vectorizer.transform(y)
print(tfidf_evaluate.shape)

(1048,)
(1048, 7788)


In [40]:
#from sklearn.neighbors import KNeighborsClassifier
#knn = KNeighborsClassifier()
#y_train_vec = tfidf_vectorizer.fit_transform(y_train)
#knn.fit(tfidf_train,y_train)
prediction = knn.predict(tfidf_evaluate)
#y_test_vec = tfidf_vectorizer.transform(y_test)
#score = accuracy_score(y_test, prediction)
#print("accuracy:   %0.3f" % score)
print(prediction)

[0 0 0 ... 0 0 0]


In [41]:
#from sklearn.naive_bayes import MultinomialNB
#clf = MultinomialNB() 
#y_train_vec = tfidf_vectorizer.fit_transform(y_train)
#y_test_vec = tfidf_vectorizer.transform(y_test)
#clf.fit(tfidf_train, y_train)
pred = clf.predict(tfidf_evaluate)
print(pred)
#score = accuracy_score(y_test, pred)
#print("accuracy:   %0.3f" % score)

[0 0 0 ... 0 0 0]


In [0]:
predictrf = rf.predict(tfidf_evaluate)

In [43]:
print(predictrf)

[0 0 0 ... 0 0 0]
